### ISSUE TITLE
is it worth having a fork for this?

### ISSUE THREAD

**Issue by 3nids** [Gaurav0/backport#37]
I had to do something similar for the key obfuscation in another workflow (creating issue in another repo triggered by PR on forks).
I have replicated your idea, but created a dedicated action for this: https://github.com/opengisch/clear-token
I am thinking to chaining this action with the original backport action.

**Comment by Gaurav0** [comment]
There are other changes I've made.

You should make people aware of the security implications of providing a key this way, but nice work!

**Comment by 3nids** [comment]
ok, thanks for the feedback
