### ISSUE TITLE
How do I "Obfuscate the personal access token by xor'ing it"

### ISSUE THREAD

**Issue by kbevers** [Gaurav0/backport#39]
Step 6 in the install guide confuses me. It is not immediately clear to me how I am supposed to obfuscate the access token. Can you offer some advice?

**Comment by Gaurav0** [comment]
Generate a random key the same length as the token using, for example, https://www.browserling.com/tools/random-hex

Then xor it with your token using, for example, https://www.browserling.com/tools/xor-encrypt

**Comment by kbevers** [comment]
Got it, thanks!

**Comment by PeterPetrik** [comment]
hmm the online xor-encypt creates string in form 
54-58-55-07-00-50-55-52-0c-57-54-02-.....

this one looks maybe better: https://md5decrypt.net/en/Xor/
